# 服务的端口，默认为 13000
# port = 13000

# 日志等级，支持：error, warn, info, debug, trace
log_level = "debug"

# 事件保留天数，默认为 7 天
event_retain_days = 10

[storage.mysql]
host = "192.168.124.37"
port = 3306
username = "root"
password = "123456"
db_name = "halia"