[package]
name = "connectors"
version.workspace = true
edition.workspace = true

[dependencies]
rumqttd = "0.19.0"

tokio = { workspace = true }
types = { workspace = true }
common = { workspace = true }
uuid = { workspace = true }
