[package]
name = "halia-derive"
version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true }
syn = { version = "2.0.89", features = ["full"] }
quote = "1.0.37"