[package]
name = "rule"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
message = { workspace = true }
operators = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
types = { workspace = true }
uuid = { workspace = true }
source = { workspace = true }
sink = { workspace = true }
functions = { workspace = true }
common = { workspace = true }
