[package]
name = "events"
version.workspace = true
edition.workspace = true

[dependencies]
common = { workspace = true }
storage = { workspace = true }

anyhow = { workspace = true }
tracing = { workspace = true }
types = { workspace = true }
