[package]
name = "utils"
version.workspace = true
edition.workspace = true

[dependencies]
storage = { workspace = true }
types = { workspace = true }
events = { workspace = true }

futures = { workspace = true }
