[package]
name = "storage"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
types = { workspace = true }
common = { workspace = true }
serde_json = { workspace = true }
