pub mod abs;
// TODO 如何定义参数
// pub mod bitand;
// pub mod bitnot;
// pub mod bitor;
// pub mod bitxor;
pub mod cbrt;
pub mod ceil;
pub mod degrees;
pub mod exp;
pub mod exp2;
pub mod floor;
pub mod ln;
// mod log;
// mod power;
pub mod add;
pub mod division;
pub mod modulo;
pub mod multi;
pub mod random;
pub mod round;
pub mod sin;
pub mod sub;
