[package]
name = "common"
version.workspace = true
edition.workspace = true

[dependencies]
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
anyhow = { workspace = true }
bytes = { workspace = true }
